### ISSUE TITLE
saltConcentration

### ISSUE THREAD

**Issue by ErikMollers** [ErikMollers/Bachelor_Thesis#3]
Hi @SanliFaez,

I'm done processing the data from the first simulation of the saltConcentration code, and I think something went wrong. There is a linear relation between the concentration of ions and the distance from the electrode, I expected the relation to be something else then linear because of shielding effects. The only thing reason that I can think off to see a linear correlation is that I put the beginning ion concentrations too low for any shielding effects to occur. 
![saltConcentration_firstRun](https://user-images.githubusercontent.com/64592913/81567973-6614a900-939d-11ea-9426-9e0ca054ee31.png)

#### variable settings used
* anion charge = -1
* anion/cation diffusivitys = 1e-9
* cation charge = 1
*  anion/cation conentrations = 9.5e-5 (in mol per cubic meters)
* potential electrode = 0.025v
* Length of the simulation domain = 40nm
* Temperature = 300k

I forgot to take a note of how to set each variable after our talk last thursday, so maybe something went wrong in these settings. What are your thoughts about the results and how should I change the variables for the next simulation?

**Comment by ErikMollers** [comment]
I figured out what went wrong, I made a mistake with the mesh. I'll upload some better graphs later today/tomorrow

**Comment by ErikMollers** [comment]
![saltConcentration_originalDomainFixed](https://user-images.githubusercontent.com/64592913/81916144-bb3a0000-95d3-11ea-88db-89faccf1dda0.png)

These results were obtained with the exact same variable settings as the above results, but with the correction to the mesh. There is no more linear correlation which is a good sign. I did however expect the concentration far away from the electrode to be the same for the cations and the anions because the potential should be shielded by the EDL formed. Maybe this isn't the case because the size of the EDL is bigger then the size of the simulated domain. So i tried the same simulation with a bigger domain, 4 micrometer instead of 40 nanometer, with this size the concentrations were also not the same far away from the electrode. 

![saltConventration_bigDomainFixed](https://user-images.githubusercontent.com/64592913/81917094-07d20b00-95d5-11ea-9419-e931fd9dbee9.png)

**Comment by SanliFaez** [comment]
these results look plausible, what is the temporal profile of the electric field? is it a pulse or oscillatory signal?
generally, a simulation domain of 20-30 debye length is okay. the relevant timescales for equilibration are (in order of long to short) L^2/D, L/kD and 1/k^D with L the size of the cell and k = 1/debye length
would be best if you also label you axis in terms of this parameter 1/k for length and L^2/D for time

**Comment by ErikMollers** [comment]
I'm not sure what "the temporal profile of the electric field" means. I fixed the potential of the bottem electrode at 0.025v and the potential at the top electrode at 0v, this is what creates the electric field.

I converted the length and time to the dimensionless parameters you suggested. It seems I have to either up the concentration or increase the simulation domain to get a simulation domain of 20-30 debye lengths
![saltConventration_bigDomainFixed(2)](https://user-images.githubusercontent.com/64592913/81926606-7f5a6700-95e2-11ea-9006-942213f610f2.png)

**Comment by ErikMollers** [comment]
Hi @SanliFaez,

I'm having some problems understanding how to implement the gouy chapman model to calculate the ion concentrations. [this](https://www.comsol.nl/paper/download/44928/Gongadze.pdf) was the paper that helped me understand the derivation. I believe equation 14 in that paper is the sinh function that you were referring to using. 

The biggest problem is see with this equation is that it only consists of constants (potential of electrode, temperature, boltzmann constant, starting ion concentration and permitivity). As far as I can see, this will produce a single value for the charge density which can not be converted into a function of ion concentrations at different positions.

**Comment by SanliFaez** [comment]
Yes, that equation is only for the density at the diffuse layer (for potentials <50 mV, same as the electrode). Having the surface charge density at the diffuse layer, you can use the debye-huckel approximation to solve the Poisson equation (pure electrostatics) and get the potential as a function of distance, which is exponentially decaying into the bulk. if your salt consists of only one ion specie (not realistic) this will give you the actual ion distribution, otherwise, it will give you (c+ - c-), which you can compare with that of your simulation.

the debye-huckel approximation is explained in the lecture-note I shared with you on teams

**Comment by ErikMollers** [comment]
Hi @SanliFaez 

These are the results of the simulation, the potential goes to 0 at the end of the simulation domain because of the boundary condition (v=0) I imposed on the electrode there. I'm not sure if this is physically the correct way to do it. We mentioned before I should imagine this electrode being grounded so this would indeed fix its potential at 0, but I feel like there shouldn't be an EDL forming here. I've looked for an other boundary condition that maybe calculate the value here by interpolation of the surroundings, so far I haven't found a good replacement. Do you think that I need to change this boundary condition or that it's fine like this?
![saktConcentration_1mM](https://user-images.githubusercontent.com/64592913/82216819-ccf40e00-9919-11ea-8f44-95dea5978d6d.png)

I haven't figured out how to calculate the ion concentration yet. I did figure out how to solve the Poisson equation in the Debye-Huckel limit but I don't know how to link this to the surface charge density of the Gouy-Chapman model. I added the pdf file with my thought process. 
[Derivation_ion_concentration.pdf](https://github.com/ErikMollers/Bachelor_Thesis/files/4644311/Derivation_ion_concentration.pdf)

**Comment by SanliFaez** [comment]
I think this looks exactly how it should look like. Very well done. putting V=0 at counter electrode is fine, but you can also put that to minus the potential of the main electrode to make it symmertric. In your case, the potential of the bulk is raise relative to the ground so you still get an electric field and that is why the EDL is formed. The result you have plotted looks absolutely good.

**Comment by ErikMollers** [comment]
Hi @SanliFaez , 

I think I got the timedependent ACpotential case up and running. I kept most parameters the same as with the DCpotential case above. The potential at the bottem electrode is described by 0.025sin(200 x pi x t), so every 0.01 seconds it goes through 1 cycle with an amplitude of 25mV. 
![saltConcentration_timeDep_secondRun](https://user-images.githubusercontent.com/64592913/82664414-fa023280-9c31-11ea-99b1-c338f068e78f.png)

Which direction should I take the simulation, you mentioned we should compare the results with another simulation so lets do that first. Should I continue working on the simulation of the electrically charged sphere next to the electrode after this, or should I do some more work with the ACpotential case maybe looking at the AREF's produced by ions with different diffusion constants as described in the papers you send me a while back.
